name: Node.js CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22,4,10,16 * * *' # Runs at 22:00, 04:00, 10:00, and 16:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout THEO-MDV2 repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install libraries
        run: npm install

      - name: Start Suhail-Md
        env:
          OWNER_NAME: ""
          OWNER_NUMBER: ""
          SESSION_ID: ""
        run: |
          timeout 6h npm start
